# Generated by Django 3.2.9 on 2021-12-08 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Articles',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_10th',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_1st',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_2nd',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_3rd',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_4th',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_5th',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_6th',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_7th',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_8th',
            field=models.IntegerField(blank=True, default=8),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='option_point_9th',
            field=models.IntegerField(blank=True, default=9),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_text',
            field=ckeditor.fields.RichTextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_1st',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_2nd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_3rd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_4th',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
