# Generated by Django 3.2.4 on 2021-06-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innercategories',
            old_name='innerCategory',
            new_name='innercategory',
        ),
        migrations.RemoveField(
            model_name='innercategories',
            name='background',
        ),
    ]
