# Generated by Django 3.2.4 on 2021-06-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innercategories',
            options={},
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='innerCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.innercategories'),
        ),
    ]
