# Generated by Django 3.2.4 on 2021-06-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210614_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointy_questions',
            name='innerCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.innercategories'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='innerCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.innercategories'),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='innerCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.innercategories'),
        ),
    ]
