# Generated by Django 3.2.4 on 2021-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210608_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
