# Generated by Django 3.2.4 on 2021-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210612_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innercategories',
            old_name='innercategory',
            new_name='innerCategory',
        ),
        migrations.AddField(
            model_name='innercategories',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', upload_to='app/static/img/Inner-Category'),
        ),
    ]
