# Generated by Django 3.2.4 on 2021-06-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210612_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innercategories',
            name='background',
        ),
    ]
