# Generated by Django 3.2.4 on 2021-06-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('category', models.CharField(default=None, max_length=200)),
                ('innerCategory', models.CharField(default=None, max_length=200)),
                ('title', models.CharField(default=None, max_length=200)),
                ('monthly_views', models.IntegerField(default=None, max_length=200)),
                ('views', models.IntegerField(default=None, max_length=200)),
                ('publish', models.DateTimeField(default=datetime.datetime.now, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
