# Generated by Django 3.2.4 on 2021-06-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_innercategories_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innercategories',
            name='background',
        ),
    ]
