# Generated by Django 3.2.4 on 2021-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210608_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='monthly_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
