# Generated by Django 3.2.4 on 2021-06-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_innercategories_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='views',
            new_name='viewssssssssssssss',
        ),
    ]
