# Generated by Django 3.2.4 on 2021-06-14 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210614_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('celebrity', 'celebrity'), ('movie-series', 'movie-series'), ('psychology', 'psychology'), ('gaming', 'gaming')], default=None, max_length=200)),
                ('title', models.CharField(default=None, max_length=200)),
                ('background', models.ImageField(default='app/static/img/Base/NotExist.jpg', upload_to='app/static/img/Inner-Category')),
                ('monthly_views', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='innercategories',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.category'),
        ),
    ]
