# Generated by Django 3.2.4 on 2021-06-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_views_quizzes_viewssssssssssssss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='viewssssssssssssss',
            new_name='views',
        ),
    ]
