# Generated by Django 3.2.4 on 2021-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_viewssssssssssssss_quizzes_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='innercategories',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', upload_to='app/static/img/Inner-Category'),
        ),
    ]
