# Generated by Django 3.2.4 on 2021-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_categories_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'کتگوری ها', 'verbose_name_plural': 'کتگوری ها'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
