# Generated by Django 3.2.4 on 2021-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_innercategories_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_10',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_7',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_8',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_pointy_questions',
            name='option_Point_9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
