# Generated by Django 3.2.4 on 2021-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210612_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_10',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_4',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_5',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_6',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_7',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_8',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_9',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
