# Generated by Django 3.2.4 on 2021-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210612_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_10',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_7',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_8',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
