# Generated by Django 3.2.4 on 2021-06-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210612_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_Pointy_Questions',
            new_name='Pointy_Questions',
        ),
        migrations.RenameModel(
            old_name='Quiz_Questions',
            new_name='Questions',
        ),
    ]
