# Generated by Django 3.2.4 on 2021-06-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210612_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointy_questions',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='quizzes_pointy',
            name='title_english',
        ),
    ]
