# Generated by Django 3.2.4 on 2021-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_quiz_questions_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='option_1',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_2',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_3',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_4',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
