# Generated by Django 3.2.4 on 2021-06-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210613_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innercategories',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
