# Generated by Django 3.2.4 on 2021-06-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_category'),
        ('app', '0020_auto_20210614_2106'),
    ]

    operations = [
    ]
