# Generated by Django 3.2.4 on 2021-06-14 18:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210614_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_1',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_10',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_2',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_3',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_4',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_5',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_6',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_7',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_8',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_9',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
