# Generated by Django 3.2.4 on 2021-06-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210614_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('celebrity', 'celebrity'), ('movie-series', 'movie-series'), ('psychology', 'psychology'), ('gaming', 'gaming')], default=None, max_length=200)),
                ('subCategory', models.CharField(default=None, max_length=200)),
                ('title', models.CharField(default=None, max_length=200)),
                ('background', models.ImageField(default='app/static/img/Base/NotExist.jpg', upload_to='app/static/img/Sub-Category')),
                ('monthly_views', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='InnerCategories',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='innerCategory',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='innerCategory',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='innerCategory',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='quizzes_pointy',
            old_name='innerCategory',
            new_name='subCategory',
        ),
    ]
