# Generated by Django 3.2.4 on 2021-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210609_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_pointy_questions',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz_pointy_questions',
            name='title_english',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
