# Generated by Django 3.2.4 on 2021-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='title',
            field=models.CharField(default=None, help_text='same quiz title', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, help_text='same quiz title', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF100',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='img or gif up to score 100%', upload_to='app/static/img/Answer-And-Result-ImGIf'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF20',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='img or gif up to score 20%', upload_to='app/static/img/Answer-And-Result-ImGIf'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF40',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='img or gif up to score 40%', upload_to='app/static/img/Answer-And-Result-ImGIf'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF60',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='img or gif up to score 60%', upload_to='app/static/img/Answer-And-Result-ImGIf'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF80',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='img or gif up to score 80%', upload_to='app/static/img/Answer-And-Result-ImGIf'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='background of playing quiz and thumb nail of quiz', upload_to='app/static/img/Quizzes'),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='background of playing quiz and thumb nail of quiz', upload_to='app/static/img/Quizzes'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='background of choosing subCategory', upload_to='app/static/img/Sub-Category'),
        ),
    ]
