# Generated by Django 3.2.4 on 2021-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210615_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='slug',
            field=models.SlugField(default=None, help_text='same as title', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default=None, help_text='same as subCategory', max_length=200),
        ),
    ]
