# Generated by Django 3.2.4 on 2021-06-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210615_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='slug',
        ),
    ]
