# Generated by Django 3.2.4 on 2021-06-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210610_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Newsletter_Users',
        ),
    ]
