# Generated by Django 3.2.4 on 2021-06-17 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210615_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('celebrity', 'celebrity'), ('movie-series', 'movie-series'), ('psychology', 'psychology'), ('gaming', 'gaming')], default=None, max_length=200)),
                ('monthly_views', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
