# Generated by Django 3.2.4 on 2021-06-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_users',
            name='favorite_Category',
        ),
    ]
