# Generated by Django 3.2.4 on 2021-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_newsletter_users_favorite_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnil_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('Thumbnil_SubCategory', models.ImageField(blank=True, default='app/static/img/Base/NotExist.jpg', null=True, upload_to='app/static/img/Thn-Category')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnil_SubCategory_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='background',
            field=models.ImageField(default='app/static/img/Base/NotExist.jpg', help_text='background of choosing quizzes | name of the file should be the title', upload_to='app/static/img/Sub-Category'),
        ),
    ]
