# Generated by Django 3.2.4 on 2021-06-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210619_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnil_SubCategory_Admin',
        ),
    ]
