# Generated by Django 3.2.4 on 2021-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='tags',
            field=models.CharField(default='کوییز', max_length=200),
        ),
    ]
