# Generated by Django 3.2.4 on 2021-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_quizzes_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes_pointy',
            name='tags',
            field=models.CharField(default='کوییز', max_length=200),
        ),
        migrations.AddField(
            model_name='quizzes_pointy',
            name='thumbnail',
            field=models.ImageField(default='NotExist.jpg', help_text='thumbnail of quiz', upload_to='QuizzesThumbnail'),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='background',
            field=models.ImageField(default='NotExist.jpg', help_text='background of playing quiz', upload_to='Quizzes'),
        ),
    ]
