# Generated by Django 3.2.4 on 2021-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210830_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_1',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_10',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_2',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_3',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_4',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_5',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_6',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_7',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_8',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Point_9',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_1',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_10',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_2',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_3',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_4',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_5',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_6',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_7',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_8',
        ),
        migrations.RemoveField(
            model_name='pointy_questions',
            name='option_Value_9',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_1_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_2_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_3_img',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option_4_img',
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_10th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_1st',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_2nd',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_3rd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_4th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_5th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_6th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_7th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_8th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_9th',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_10th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_1st',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_2nd',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_3rd',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_4th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_5th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_6th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_7th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_8th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_Point_9th',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_10th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_1st',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_2st',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_3rd',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_4th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_5th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_6th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_7th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_8th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='option_img_9th',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='pointy_questions',
            name='question_img',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_1st',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_1st_img',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_2nd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_2nd_img',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_3rd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_3rd_img',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_4th',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option_4th_img',
            field=models.ImageField(default='NotExist.jpg', upload_to='Question-Option-Imgs'),
        ),
    ]
