# Generated by Django 3.2.4 on 2021-08-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210830_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointy_questions',
            name='publish',
        ),
    ]
