# Generated by Django 3.2.4 on 2021-08-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_pointy_questions_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointy_questions',
            name='category',
        ),
    ]
