# Generated by Django 3.2.4 on 2021-08-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_pointy_questions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option_1st_img',
            new_name='option_img_1st',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_2nd_img',
            new_name='option_img_2nd',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_3rd_img',
            new_name='option_img_3rd',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_4th_img',
            new_name='option_img_4th',
        ),
    ]
