# Generated by Django 3.2.4 on 2021-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210831_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_10th',
            new_name='option_point_10th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_1st',
            new_name='option_point_1st',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_2nd',
            new_name='option_point_2nd',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_3rd',
            new_name='option_point_3rd',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_4th',
            new_name='option_point_4th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_5th',
            new_name='option_point_5th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_6th',
            new_name='option_point_6th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_7th',
            new_name='option_point_7th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_8th',
            new_name='option_point_8th',
        ),
        migrations.RenameField(
            model_name='pointy_questions',
            old_name='option_Point_9th',
            new_name='option_point_9th',
        ),
    ]
