# Generated by Django 3.2.4 on 2021-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210831_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointy_questions',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, help_text='same quiz title', max_length=100),
        ),
    ]
