# Generated by Django 3.2.4 on 2021-09-15 05:53

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210908_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=80)),
                ('thumbnail', models.ImageField(default=None, upload_to='QuizzesThumbnail')),
                ('content', ckeditor.fields.RichTextField(default=None)),
                ('tags', models.CharField(default=None, max_length=100)),
                ('monthly_views', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Newsletter_Users',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='pointy_questions',
            name='title',
            field=models.CharField(default=None, help_text='same quiz title', max_length=80),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, help_text='same quiz title', max_length=80),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='tags',
            field=models.CharField(default='کوییز', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='tags',
            field=models.CharField(default='کوییز', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
