# Generated by Django 3.2.4 on 2021-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='NotExist.jpg', upload_to='QuizzesThumbnail'),
        ),
    ]
