# Generated by Django 3.2.9 on 2021-11-06 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210916_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20)),
                ('email', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('avatar', models.ImageField(default='NotExist.jpg', unique=True, upload_to='profileAvatars')),
                ('joinedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('birthday', models.DateTimeField()),
                ('bio', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'مذکر'), ('Female', 'مؤنث'), ('PreferNotToSay', 'ترجیح میدم نگم')], default='Male', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('comments', models.TextField(default=None)),
                ('categoryHistory', models.TextField(default=None)),
                ('saveList', models.TextField(default=None)),
                ('playedQuizzesCounter', models.IntegerField(default=0)),
                ('averageScoreResult', models.IntegerField(default=0)),
                ('inviteUrl', models.URLField(default=None)),
            ],
        ),
    ]
