# Generated by Django 3.2.9 on 2021-11-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categoryHistory',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saveList',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
