# Generated by Django 3.2.9 on 2021-11-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20211109_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
