# Generated by Django 3.2.9 on 2021-11-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_profile_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='newsletter',
            new_name='newsletter1',
        ),
    ]
