# Generated by Django 3.2.4 on 2021-09-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210915_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
