# Generated by Django 3.2.4 on 2021-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='note',
            field=models.TextField(default='note', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
