# Generated by Django 3.2.4 on 2021-06-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210608_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='monthly_views',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='categories',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='categories',
            name='views',
            field=models.IntegerField(default=None),
        ),
    ]
