# Generated by Django 3.2.4 on 2021-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210608_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
