# Generated by Django 3.2.4 on 2021-06-08 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_categories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('category', models.CharField(default=None, max_length=100)),
                ('innerCategory', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('monthly_views', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('background', models.CharField(max_length=100)),
                ('fan_name', models.CharField(max_length=100)),
                ('GIF20', models.CharField(max_length=200)),
                ('GIF40', models.CharField(max_length=200)),
                ('GIF60', models.CharField(max_length=200)),
                ('GIF80', models.CharField(max_length=200)),
                ('GIF100', models.CharField(max_length=200)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='innerCategories',
        ),
    ]
