# Generated by Django 3.2.4 on 2021-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210608_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
