# Generated by Django 3.2.4 on 2021-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_quizzes_title_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default=None, max_length=100)),
                ('innerCategory', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('title_english', models.CharField(default=None, max_length=100)),
                ('question', models.TextField(default=None)),
                ('option_1', models.CharField(default=None, max_length=100)),
                ('option_2', models.CharField(default=None, max_length=100)),
                ('option_3', models.CharField(default=None, max_length=100)),
                ('option_4', models.CharField(default=None, max_length=100)),
                ('answer', models.IntegerField(default=1)),
                ('answer_imGif', models.CharField(default=None, max_length=200)),
                ('answer_text', models.TextField(default=None)),
            ],
        ),
    ]
