# Generated by Django 3.2.4 on 2021-06-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quiz_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_Questions',
            new_name='QuizQuestions',
        ),
    ]
