# Generated by Django 3.2.4 on 2021-06-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_quizzespointy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizzesPointy',
            new_name='Quizzes_Pointy',
        ),
    ]
