# Generated by Django 3.2.4 on 2021-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_quizzespointy_quizzes_pointy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_img_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_10',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_3',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_4',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_5',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_6',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_7',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_8',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_text_9',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_title_9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_10',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_3',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_4',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_5',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_6',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_7',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_8',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quizzes_pointy',
            name='result_upTo_9',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
