# Generated by Django 3.2.4 on 2021-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210609_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='GIF100',
            field=models.CharField(default='empty.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF20',
            field=models.CharField(default='empty.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF40',
            field=models.CharField(default='empty.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF60',
            field=models.CharField(default='empty.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='GIF80',
            field=models.CharField(default='empty.jpg', max_length=200),
        ),
    ]
