# Generated by Django 3.2.4 on 2021-06-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210609_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=200)),
                ('favorite_Category', models.CharField(default=None, max_length=200)),
                ('signedUp_On', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
